### ISSUE TITLE
Can the actual errors please be passed back to client?

### ISSUE THREAD

**Issue by andrewf414** [bigcommerce/storefront-data-hooks#110] opened 2021-11-07 21:00 UTC
Hi, I imagine this happens elsewhere, but I am looking at signup giving a generic "something went wrong" type error. Could it pass back the actual error to be more useful? e.g. "email xxxx already in use"?
https://github.com/bigcommerce/storefront-data-hooks/blob/bf5d80224e4ae44413f6538b4855f88775e47494/src/api/customers/signup.ts

**Comment by jorgemasta** [comment] 2021-11-17 12:46
Yes, it's something we contemplate, I think in those cases like login it would be quite useful.

I close as it is a duplicate of #23

**Closed by jorgemasta** 2021-11-17 12:46 UTC
