### ISSUE TITLE
Question/Request Login through SSO

### ISSUE THREAD

**Issue by rodeyseijkens** [bigcommerce/storefront-data-hooks#11] opened 2020-12-01 10:46 UTC
We are looking into using these hooks, but we have our own login system. 
How will this work in combination with the SSO?

**Comment by avisra** [comment] 2021-01-07 13:54
I'm in the same boat. These hooks appear to assume you are BC for login. Hopefully someone from the team responds to this one soon!

**Comment by amckemie** [comment] 2021-01-15 17:59
Hi all, @rodeyseijkens & @avisra can you give more detail please around what the problem is that you are running into / what the specific need is that you have around the SSO? It sounds like you are looking to abstract the SSO from data-hooks so that you can include your own login, but I don't want to make assumptions. Thanks!

**Comment by avisra** [comment] 2021-01-19 03:01
@amckemie Sure thing. My assumption is that these hooks reference the current customer via the useCustomer hook - which I believe is set via the login process (which logs in a user to a BC customer account). I have my own identity provider and auth server that I'd like to use for logging into the app (planning on using NextAuth) - but I still want to set the customer behind the scenes so the cart/checkout/etc components can reference the customer data. My identity provider already has the BC customer ID stored for each of my users.

In my current setup, I am using the BC SSO api to forcefully login users using their customer ID: https://developer.bigcommerce.com/api-reference/storefront/customer-login-sso

So I think that I'm looking for... is a way to forcefully set the BC customer that useCustomer relies on - from my own custom login process.

**Comment by magicspon** [comment] 2021-01-21 18:20
Any progress on this?

I am hitting the SSO endpoint to create a sign the users into the bigcommerce system, so that when they click on the checkout link, they are still logged in... however, if they then click edit cart, the login session is lost, forcing the user to log back in again

**Comment by avisra** [comment] 2021-02-16 02:03
Does anyone have a good workaround for this in the meantime?

**Comment by jorgemasta** [comment] 2021-02-17 11:20
I am working on it, probably today I will be able to create a PR!
We expect to have it published next week.

**Comment by avisra** [comment] 2021-02-18 02:34
This is definitely a step in the right direction. Is it possible though to retrieve this shop-token completely server-side? My understanding is their Customer Login SSO actually requires a redirection to their token endpoint b(from the customer's browser).

This is an example flow I would expect:

1. Customer comes to my NextJS site and uses NextAuth.JS to login via our auth providers. Our database already has the BC customer ID on file for all of our users. And if there is not one on file, we use the BC apis to automatically generate one and store the customer ID.
2. On authentication callback from NextAuth.JS we would initiate a server-side call to retrieve (from BC using the customer ID) and set the SHOP-TOKEN cookie.
3. This would automatically be available to the storefront data hooks and all the APIs would function as expected.

**Comment by magicspon** [comment] 2021-02-18 11:15
Does this solve the issue where a user logins in (with sso), navigates to the checkout page, then hits edit cart and is sent back to the site in a logged out state?

**Comment by jorgemasta** [comment] 2021-02-18 13:22
> This is definitely a step in the right direction. Is it possible though to retrieve this shop-token completely server-side? My understanding is their Customer Login SSO actually requires a redirection to their token endpoint b(from the customer's browser).
> 
> This is an example flow I would expect:
> 
> 1. Customer comes to my NextJS site and uses NextAuth.JS to login via our auth providers. Our database already has the BC customer ID on file for all of our users. And if there is not one on file, we use the BC apis to automatically generate one and store the customer ID.
> 2. On authentication callback from NextAuth.JS we would initiate a server-side call to retrieve (from BC using the customer ID) and set the SHOP-TOKEN cookie.
> 3. This would automatically be available to the storefront data hooks and all the APIs would function as expected.
> 
> Reviewing your example, I am having a hard time understanding the use case of the useLogin hook in the event we already have our own login/authentication mechanism (e.g. we are using NextAuth.JS and IdentityServer4).
> 
> I will tinker with this some more.

Yes, the Custom Login SSO requires a redirect but you can do it in the server as well:
1. Generate the Login SSO URL 
2. Fetch that URL (with `redirect: "manual") in the server to obtain the tokens
3. Find and return the `SHOP_TOKEN`

[Example](https://gist.github.com/jorgemasta/c709b63501344970026f3a3e7646cc77#file-sso-login-ts-L40-L42)

The benefit of using the `useLogin` is that it forces to revalidate the `useCustomer`.

In your case, I think you have these options:

- As you said, set the SHOP-TOKEN in the authentication callback from NextAuth (is this possible?) and manually revalidate the `useCustomer` hook. In this case is not necessary the `useLogin` hook.
- **Don't** use the `signIn` method from NextAuth Create and create a new API route to handle all the authentication. In that new route you can POST `/api/auth/signin/:provider ` and if everything is OK get and return the SHOP_TOKEN. Use this new API route as the `url` option of the `useLogin`.

Makes sense? @avisra

**Comment by jorgemasta** [comment] 2021-02-18 13:25
> Does this solve the issue where a user logins in (with sso), navigates to the checkout page, then hits edit cart and is sent back to the site in a logged out state?

Yes, it should. In the end, login (with or without sso) means that we store the SHOP_TOKEN cookie. Do you have any examples you can show of the problem you have?

**Comment by magicspon** [comment] 2021-02-18 14:16
example here:

https://oomphmade.com/pricing/cards

user adds item to cart
logins in
goes to checkout
presses edit cart (on bc)
goes back to cart, the user is now logged out of the next frontend

**Comment by magicspon** [comment] 2021-02-18 14:34
@avisra 
> 1. Our database already has the BC customer ID on file for all of our users.

Can I ask how you've achieved this?

**Comment by jorgemasta** [comment] 2021-02-18 15:52
> example here:
> 
> https://oomphmade.com/pricing/cards
> 
> user adds item to cart
> logins in
> goes to checkout
> presses edit cart (on bc)
> goes back to cart, the user is now logged out of the next frontend

This is probably because the checkout page is not part of your Next App, you are redirected to your "main" store. From https://oomphmade.com/cart to https://oomph-made.mybigcommerce.com/checkout.

**Comment by magicspon** [comment] 2021-02-18 17:10
This is true... However, the login session is usually saved. if i login, then close the browser, then reopen, I am still logged in.
has there been any progress on supporting the embedded checkout? 

I had a play with the method:
https://github.com/bigcommerce/storefront-data-hooks/issues/6

But was always getting an error saying the cart is empty, even though i had stuff in my cart.

**Comment by avisra** [comment] 2021-02-22 18:16
>     * As you said, set the SHOP-TOKEN in the authentication callback from NextAuth (is this possible?) and manually revalidate the `useCustomer` hook. In this case is not necessary the `useLogin` hook.

Yes I believe this makes sense. I have the code setup on my side - and have been able to set the SHOP_TOKEN cookie on my NextAuth callback. But how can I revalidate the useCustomer hook like you mention in the first option?

**Comment by jorgemasta** [comment] 2021-02-23 12:02
> > ```
> > * As you said, set the SHOP-TOKEN in the authentication callback from NextAuth (is this possible?) and manually revalidate the `useCustomer` hook. In this case is not necessary the `useLogin` hook.
> > ```
> 
> Yes I believe this makes sense. I have the code setup on my side - and have been able to set the SHOP_TOKEN cookie on my NextAuth callback. But how can I revalidate the useCustomer hook like you mention in the first option?

Cool, how did you manage to set the SHOP_TOKEN cookie? Is similar to [this gist](https://gist.github.com/jorgemasta/c709b63501344970026f3a3e7646cc77#file-sso-login-ts)?

To revalidate the `useCustomer` you have to call the `revalidate` method. E.g:
https://github.com/bigcommerce/storefront-data-hooks/blob/034be1e4c7fa363f4b1362fd1a6d50e25b2632ea/src/use-login.tsx#L36-L42
This will force the customer data to be updated.

**Comment by avisra** [comment] 2021-02-24 05:39
Awesome. Thanks a bunch for this. I have the SHOP_TOKEN being retrieved and added on login via NextAuth. And revalidating the customer using revalidate() is showing the customer information coming back properly, which is awesome. However, I noticed two issues that I may need assistance with:

1. After logging in (and revalidating the customer) - going to checkout (redirects to bigcommerce checkout page - e.g. same as what Vercel commerce is doing) the user is not logged in - it is displaying guest checkout and has the option for user to login there. I would expect that the BC checkout page would know who the user is.

2. I noticed that SHOP_TOKEN does not always come back from the fetch call. If I do it too quickly in succession, I will get SHOP_SESSION_TOKEN and a few others - but not SHOP_TOKEN.

**Comment by magicspon** [comment] 2021-02-24 09:07
I am seeing the same as @avisra

**Comment by jorgemasta** [comment] 2021-02-24 12:23
What are you seeing @magicspon ? 1 or 2?

**Comment by jorgemasta** [comment] 2021-02-24 12:25
I have created a new ticket for 1 (#36).
About 2, can you provide more info in a new ticket? @avisra 

I close this ticket in favor of the new ones as a solution for the Login SSO will be included in the next release.

**Closed by jorgemasta** 2021-02-24 12:25 UTC
Labels: authentication, enhancement

**Comment by magicspon** [comment] 2021-02-24 12:59
@jorgemasta 1 and 2.

A logged in user goes to the checkout and is logged out.
Also, seeing `SHOP_SESSION_TOKEN` rather than `SHOP_TOKEN `

**Comment by ahmadsyed** [comment] 2021-03-05 14:49
@magicspon, @jorgemasta, did anyone got it working. As of now when I am clicking at checkout from nextjs commerce store, it goes to BC store checkout as a guest user. I want that my customer don't have to login again there.

**Comment by avisra** [comment] 2021-03-05 17:02
I did, but it was a doozie.

I have two apps:
shop.mysite.com (BigCommerce)
www.mysite.com (my headless shop)

First, it is important that your headless shop create the shop_token/shop_session_token with the TLD mysite.com instead of www.mysite.com (otherwise the shop will not be able to use it).

Second - and this one is unfortunate - but BigCommerce has a weird quirk where it will attempt to create a new shop_session_token even though one exists already at the TLD. The first time it does this, it will be the correct value - but on the shop.mysite.com domain. The second time it does this, it will be a different value and it won't work (use will be guest).

To solve this problem.. I used a Cloudflare worker. Both subdomains are hosted through my CloudFlare account. So, I added a worker that replaces the "SHOP_SESSION_TOKEN" domain in the Set-Cookie header. This worked flawlessly - after much tinkering.

**Comment by magicspon** [comment] 2021-03-05 17:18
I'm having some issues using the updated useLogin hook:

```javascript
const login = useLogin({
	url: "/api/auth/sso",
})

const onSubmit = async (formData) => {
	login({
		email: formData.email,
		password: formData.password,
	})
}
```

if the wrong email/password is provided, an error is Thrown.
![image](https://user-images.githubusercontent.com/3268717/110149929-8901c500-7dd6-11eb-9b25-61429ca0ab83.png)

And the `api/auth/sso` endpoint is never called, even with the correct email/password

Any ideas

**Comment by magicspon** [comment] 2021-03-07 15:08
@avisra 
are you using the new useLogin hook?

**Comment by ahmadsyed** [comment] 2021-03-07 15:55
@avisra,
It looks like 
1- You are using your own auth while I am using build-in (That comes with nextJs boilerplate).
2- Then with the help of domain/subdomain settings, you are setting cookies on the parent domain & utilizing them on the child domain.

Did I get both points right? If yes, Then will it be possible to use your flow with bigcommerce built-in auth?
@magicspon which scenario you are using? build-in or your own auth provider?

**Comment by magicspon** [comment] 2021-03-07 19:19
I'm using my own auth provider (via craftcms). 
I successfully managed to login the user with SSO, using my own hook. However, i'd rather use the hook provided with my own auth.

**Comment by magicspon** [comment] 2021-03-08 13:04
I believe there is an error in the docs:

this works: 
```
	const login = useLogin({
		options: {
			url: "/api/auth/sso",
		},
	})
```

**Comment by magicspon** [comment] 2021-03-08 14:52
I'm getting a `200` response status from calling my sso endpoint.
Then i'm immediately getting a 500 internal server error from the `/api/bigcommerce/customers` endpoint
![image](https://user-images.githubusercontent.com/3268717/110337432-d3c14e00-801d-11eb-86d2-52020ea4cd5c.png)


@jorgemasta I'm using your SSO example (modified slightly)

https://gist.github.com/magicspon/f3617e8d12db7cb46199283d2b043272

**Comment by magicspon** [comment] 2021-03-08 15:23
Sorted... 
Created a new API Account.  now it's working as expected
@jorgemasta thanks for your work on this, greatly appreciated
